--liquibase formatted sql
--changeset kdomian:31
CREATE TABLE PRICING(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRICE DOUBLE NOT NULL,
    PASS_TYPE INT NOT NULL,
    PERIOD_ID BIGINT NOT NULL
);

--changeset kdomian:32
ALTER TABLE PRICING
    ADD CONSTRAINT PRICING_PERIOD_ID
        FOREIGN KEY (PERIOD_ID) REFERENCES PERIOD(ID);

--changeset kdomian:33
INSERT INTO PRICING VALUES ( NULL, 124.00, 1, 1 );
INSERT INTO PRICING VALUES ( NULL, 134.00, 2, 1 );
INSERT INTO PRICING VALUES ( NULL, 145.00, 1, 2 );
