--liquibase formatted sql
--changeset kdomian:41
CREATE TABLE TARIFF(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PERIOD_ID BIGINT NOT NULL,
    TICKET_ID BIGINT NOT NULL,
    PRICE DOUBLE NOT NULL
);

--changeset kdomian:42
ALTER TABLE TARIFF
    ADD CONSTRAINT TARIFF_PERIOD_ID
        FOREIGN KEY (PERIOD_ID) REFERENCES PERIOD(ID);
ALTER TABLE TARIFF
    ADD CONSTRAINT TARIFF_TICKET_ID
        FOREIGN KEY (TICKET_ID) REFERENCES TICKET(ID);

--changeset kdomian:43
INSERT INTO TARIFF VALUES ( NULL, 1, 2, 75.0 );
INSERT INTO TARIFF VALUES ( NULL, 1, 1, 85.0 );
INSERT INTO TARIFF VALUES ( NULL, 2, 3, 100.0 );
INSERT INTO TARIFF VALUES ( NULL, 2, 1, 65.0 );
INSERT INTO TARIFF VALUES ( NULL, 2, 2, 75.0 );
INSERT INTO TARIFF VALUES ( NULL, 3, 2, 115.0 );
